### ISSUE TITLE
ZCash is under attack (DM Article)

### ISSUE THREAD

**Issue by PhoenixGreen** [xaur/decred-issues#149]
I'm looking for quotes, thoughts and investigations that look into the current spam attack on the ZCash network. What I have so far:

Tweet link - https://twitter.com/xenumonero/status/1577544987612520448?s=61&t=Argeky50nWJ4f2YfWJHI-w
The zcash spam attack continues. Almost every block contains a shielded transaction with hundreds of outputs. In doing so, the spammer can successfully blow up the size of the chain by maxing each 2mb block every 75 seconds. The cost of each spammed transaction? Less than a cent. See for yourself!

“I thought txs must have just been really large and that accounted for the massive size of the chain, but in retrospect the tx count also didn't make sense, figured someone was churning to make them look active.” @JZ

“The node count also seems way off went from 200 to 8k. There's no way there are more ZEC nodes than BTC nodes especially at this chain size.- https://blockchair.com/zcash/nodes “ @JZ

ZCash Foundation response - https://twitter.com/reldev/status/1578589120024100864?s=61&t=OJuRmQ77G3-eJmCB8p5I3Q

Ex Decred member Micheal2xl suggested Decred had been under a similar attack from BTC maxis years ago - https://twitter.com/michae2xl/status/1578544908289179648?s=61&t=OJuRmQ77G3-eJmCB8p5I3Q

When asked, lead developer Dave Collins said, “I've seen a few attempts of various things in that vein, but they aren't really effective because fees are based on tx size, so it costs the same regardless, and the max block size is intentionally low because we can easily change it via a stakeholder vote when genuine organic demand requires it.”

**Comment by xaur** [comment]
Published: https://www.decredmagazine.com/zcash-is-under-attack/
