### ISSUE TITLE
Rename Decred

### ISSUE THREAD

**Issue by xaur** [xaur/decred-issues#75]
Decred stands for decentralized credit.

The idea to rename Decred came up many times. I believe it is settled for now. For historic reference, and to have something to share in case this ever comes up again, below is an (incomplete) list of discussions of the topic.

* 2017-04-01 https://forum.decred.org/threads/name-change-proposal-decred-to-dcred.5229/
* 2017-06-18 https://www.reddit.com/r/decred/comments/6o2x07/how_does_one_get_past_the_decred_name/
* 2017-08-13 https://www.reddit.com/r/decred/comments/6ti1vs/transcript_of_proof_of_stake_name_discussion_in/
* 2017-10-25 https://www.reddit.com/r/decred/comments/78rfcw/decentralized_credit_decred/
* 2017-11-22 https://www.reddit.com/r/decred/comments/7eprzl/is_politeia_and_dao_launch_a_brand_evolution/
* 2018-05-01 https://www.reddit.com/r/decred/comments/8fw4pm/moneros_community_is_about_16x_as_big_as_ours_why/dy9f6po/

**Comment by noahpierau** [comment]
Another relevant (not related) thread: 
https://www.reddit.com/r/decred/comments/ans7lg/what_do_we_think_of_converting_decreds_ticker/

**Comment by xaur** [comment]
I think ticker is separate enough to have its own issue: #130.

**Comment by xaur** [comment]
Nice article [Why the name Decred is awesome](https://medium.com/decred/why-the-name-decred-is-awesome-9627ae9b4e2) + triggered a [discussion](https://www.reddit.com/r/decred/comments/c2uy85/why_the_name_decred_is_awesome/).

**Comment by xaur** [comment]
[Decred's Name Sucks and I'm Glad!](https://medium.com/@dlefebvr/decreds-name-sucks-and-i-m-glad-853af487034e)

**Comment by xaur** [comment]
Hey @Dustorf, when someone questions the name Decred you can send them here :)

**Comment by xaur** [comment]
https://www.reddit.com/r/decred/comments/hh2ult/a_better_name_for_decred_to_broaden_the_reach_of/

**Comment by xaur** [comment]
https://www.reddit.com/r/decred/comments/kpjte8/change_decred_name_to_another_without_any/
